### ISSUE TITLE
Great Work! Suggestions for Including Related Work in Your Paper

### ISSUE THREAD

**Issue by bbsngg** [OpenGVLab/MM-NIAH#2]
Hi Weiyun,

Thank you for your significant contribution with this impressive work.

We would like to kindly draw your attention to our previous work, [MileBench](https://arxiv.org/abs/2404.18532), which also includes multimodal "needle in a haystack" data for benchmarking multimodal LLMs. Our work also uses synthetic data to build the dataset, although it is not as diverse as MM-NIAH. Given the comprehensive setting in your work, we believe that referencing MileBench would be a valuable addition to your related work section.

Thank you for your consideration.

**Comment by Weiyun1025** [comment]
Thank you for your interest in our work, and congratulations on your outstanding achievements. We will include a discussion of your work in the related work section of the next edition of our paper.

**Comment by bbsngg** [comment]
Thank you for your positive response. We are excited to see more of your fascinating contributions in the future.
